name: Rust

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: wasm-pack build --release
    - name: Run tests
      run: cargo test
    - name: Run integration tests
      run: wasm-pack test --headless --chrome --firefox
